export const SERVICOS = [
  'Tradução Simples',
  'Tradução Juramentada',
  'Interpretação Simultânea',
  'Interpretação em Libras',
  'Revisão de documento',
  'Transcrição',
  'Legendagem',
  'Outros',
] as const;

export const IDIOMAS = [
  'Albanês',
  'Alemão',
  'Árabe (Egito)',
  'Búlgaro',
  'Catalão',
  'Chinês (Simp-HK)',
  'Chinês (Simp-Mandarim)',
  'Chinês (Trad-Cantonês)',
  'Chinês (Trad-TW)',
  'Coreano',
  'Crioulo Haitiano',
  'Croata',
  'Dinamarquês',
  'Eslovaco',
  'Esloveno',
  'Espanhol (Argentina)',
  'Espanhol (Espanha)',
  'Espanhol (LATAM)',
  'Espanhol (México)',
  'Finlandês',
  'Francês (Canadá)',
  'Francês (França)',
  'Grego',
  'Hebraico',
  'Hindi',
  'Holandês',
  'Húngaro',
  'Inglês (Austrália)',
  'Inglês (Canadá)',
  'Inglês (EUA)',
  'Inglês (Reino Unido)',
  'Italiano',
  'Japonês',
  'Laosiano',
  'Latim',
  'Letão',
  'LIBRAS',
  'Lituano',
  'Malaio',
  'Mongol',
  'Norueguês (Bokmål)',
  'Persa',
  'Polonês',
  'Português (Angola)',
  'Português (Brasil)',
  'Português (Moçambique)',
  'Português (Portugal)',
  'Romeno',
  'Russo',
  'Sérvio (Cirílico)',
  'Sérvio (Latim)',
  'Somali',
  'Sueco',
  'Tailandês',
  'Tcheco',
  'Turco',
  'Ucraniano',
  'Umbundu (Angola)',
  'Urdu',
  'Vietnamita',
] as const;