import { test, expect } from '@playwright/test';

test('intake with documents persists, reaches staff inbox and quote simulation is honest', async ({ page }, testInfo) => {
  const requests: string[] = [];
  page.on('request', request => { if (request.url().includes(':8000/requests')) requests.push(request.url()); });
  await page.goto('/');
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Preencha os campos obrigatórios');
  await page.getByLabel('Nome do projeto *', { exact: true }).fill('Manual enviado pelo site');
  await page.getByLabel('Sobre o projeto *', { exact: true }).fill('Traduzir um manual técnico com 20 páginas.');
  await page.getByRole('button', { name: 'Inverter idiomas', exact: true }).click();
  await expect(page.getByLabel('Idioma de origem *', { exact: true })).toHaveValue('Inglês');
  await expect(page.getByLabel('Idioma de destino *', { exact: true })).toHaveValue('Português');
  await page.getByRole('button', { name: 'Inverter idiomas', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'O material faz a diferença.' })).toBeVisible();
  const chooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Anexar documentos', exact: true }).click();
  await (await chooser).setFiles('tests/fixtures/sample.txt');
  await expect(page.getByText('sample.txt', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Voltar', exact: true }).click();
  await expect(page.getByLabel('Nome do projeto *', { exact: true })).toHaveValue('Manual enviado pelo site');
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByText('sample.txt', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Testar solicitação', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Preencha os campos obrigatórios');
  await page.getByLabel('Seu nome *', { exact: true }).fill('Cliente de teste');
  await page.getByLabel('E-mail *', { exact: true }).fill('client@example.test');
  await page.getByRole('checkbox', { name: 'Autorizar contato para orçamento' }).click();
  await page.getByRole('button', { name: 'Testar solicitação', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Pedido salvo na prévia.' })).toBeVisible();
  expect(requests).toEqual([]);
  await page.goto('/login');
  await page.getByRole('button', { name: 'Acessar demonstração', exact: true }).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.getByRole('button', { name: 'Ver solicitações do site', exact: true }).click();
  await page.getByRole('button', { name: /Abrir solicitação.*Manual enviado pelo site/ }).click();
  await expect(page.getByText('client@example.test', { exact: true })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'sample.txt', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('sample.txt');
  await page.getByRole('button', { name: 'Iniciar análise', exact: true }).click();
  await page.getByLabel('Valor do orçamento (R$)', { exact: true }).fill('350,50');
  await page.getByLabel('Prazo de entrega', { exact: true }).fill('5 dias úteis após aprovação');
  await page.getByRole('button', { name: 'Salvar rascunho', exact: true }).click();
  await expect(page.getByTestId('quote-notice')).toContainText('Rascunho salvo');
  await page.getByRole('button', { name: 'Fechar solicitação', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: /Abrir solicitação.*Manual enviado pelo site/ }).click();
  await expect(page.getByLabel('Valor do orçamento (R$)', { exact: true })).toHaveValue('350,50');
  await page.getByRole('button', { name: 'Revisar envio simulado', exact: true }).click();
  await expect(page.getByText('Prévia local · nenhum e-mail será enviado')).toBeVisible();
  await page.getByRole('button', { name: 'Confirmar simulação', exact: true }).click();
  await expect(page.getByTestId('quote-notice')).toContainText('Nenhum e-mail foi enviado');
  await page.getByRole('button', { name: 'Fechar solicitação', exact: true }).click();
  await expect(page.getByText('Orçamento simulado', { exact: true }).last()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Solicita\u00e7\u00e3o', exact: true })).toBeHidden();
  await page.screenshot({ path: testInfo.outputPath('requests-inbox.png') });
});
